newDesign

diff --git a/.github/workflows/notify-slack.yml b/.github/workflows/notify-slack.yml
--- a/.github/workflows/notify-slack.yml
+++ b/.github/workflows/notify-slack.yml
@@ -1,4 +1,4 @@
-name: Notify Slack
+name: Check pull request description checkbox and send notify to Slack
 
 on:
   pull_request:
@@ -6,19 +6,27 @@ on:
       - opened
       - synchronize
 
+env:
+  checkbox: "should this be added to delinea marketplace?"
+
 jobs:
   notify:
     runs-on: ubuntu-latest
 
     steps:
       - name: Check if "should this be added to delinea marketplace?" is checked
-        id: check_checkbox
+        env:
+          BODY: ${{ github.event.pull_request.body }}
         run: |
-          checked=$(grep -c "\[x\] should this be added to delinea marketplace?" main..${{ github.sha }} || true)
-          echo "CHECKED=$checked" >> $GITHUB_ENV
-
-      - name: Notify Slack
-        if: env.CHECKED == '1'
-        run: |
-          curl -X POST -H 'Content-type: application/json' --data '{"text":"New PR: ${{ github.event.pull_request.title }} by ${{ github.actor }}"}' $SLACK_WEBHOOK_URL
-
+          UNCHECKED="\[ \] $checkbox"
+          MARKED="\[x\] $checkbox"
+          if echo ${BODY,,} | grep -q "$MARKED"; then
+            curl -X POST -H 'Content-type: application/json' --data '{"text":"New PR: ${{ github.event.pull_request.title }} by ${{ github.actor }}"}' $SLACK_WEBHOOK_URL
+            exit 0
+          elif echo ${BODY,,} | grep -q "$UNCHECKED"; then
+            echo "Checkbox is not checked"
+            exit 1
+          else
+            echo "Checkbox not found in pull request description"
+            exit 1
+          fi
